### ISSUE TITLE
Solution item not returned for GetSelectedHierarchiesAsync() when selecting items and the solution item

### ISSUE THREAD

**Issue by shaggygi** [VsixCommunity/Community.VisualStudio.Toolkit#107]
I could be misinterpreting how this should work, but seems like the solution item would also return when selecting along with other items.  Use image below as example.

![image](https://user-images.githubusercontent.com/2956825/124691275-91aff800-dea9-11eb-9229-60f4f5da73ca.png)

✔️ : It returns the solution item and a count of 1 if I only select the solution item.
✔️ : It returns the folder item and a count of 1 if I only select the folder item.
✔️ : It returns both folder items (2nd folder not shown above) and a count of 2 if I select both folder items.
❌ : It returns the folder item and a count of 1 if I select the solution item and the folder item.  Seems like it would also return the solution item and a count of 2.

I've added other items (folders, projects, etc.) and get same results.  I believe the error occurs within [this if statement](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/db3fc391d24a7670dbf8d5999af7ad32a2289656/src/Community.VisualStudio.Toolkit.Shared/Selection/Selection.cs#L105) as the `hierItem` is returned null for the solution item and doesn't get added to results.

**Comment by madskristensen** [comment]
That's a good point and you're right about the if-statement. Wanna take a stab at including the solution node when the `HierarchyItem` is null?

**Comment by shaggygi** [comment]
> Wanna take a stab at including the solution node when the HierarchyItem is null?

Sure.  I started last night, but wanted to see thoughts first.  I believe there are some other issues/scenarios related, but will need to collect thoughts and write up once verified.
