### ISSUE TITLE
O(n^2) implementation in Selection.GetSelectedHierarchiesAsync

### ISSUE THREAD

**Issue by bluetarpmedia** [VsixCommunity/Community.VisualStudio.Toolkit#109]
This looks quadratic to me because `List.Contains` is O(n) and the `results` List grows in size to equal (or get close to) the size of `items`.

```
List<IVsHierarchyItem> results = new();

...

VSITEMSELECTION[] items = new VSITEMSELECTION[itemCount];
multiSelect.GetSelectedItems(0, itemCount, items);

foreach (VSITEMSELECTION item in items)
{
    IVsHierarchyItem? hierItem = await item.pHier.ToHierarcyItemAsync(item.itemid);
    if (hierItem != null && !results.Contains(hierItem))
    {
        results.Add(hierItem);
    }
}
```

Is the `results.Contains` necessary? Is there a scenario where `GetSelectedItems` returns duplicates?

If so, perhaps the method can add to `results` unconditionally and after the `foreach` completes, remove duplicates at the end.

**Comment by madskristensen** [comment]
Good question. I'm not sure why `results.Contains` was added and could likely be removed.

**Comment by bluetarpmedia** [comment]
From what I can see in the history I think it was added in 64ffb8141f3a3e5215718cafe3ae53c1304fdd6a.

I found the same code pattern in [this Extensibility sample](https://github.com/microsoft/VSSDK-Extensibility-Samples/blob/master/Code_Sweep/C%23/VsPackage/ProjectUtilities.cs). Do you remember if you copied that code? In that example, it's avoiding duplicates in the `results` list because it only wants to get the project(s) of the current selection.

**Comment by madskristensen** [comment]
I might have gotten it from that sample
