### ISSUE TITLE
Consolidate Selection and Solution classes

### ISSUE THREAD

**Issue by shaggygi** [VsixCommunity/Community.VisualStudio.Toolkit#113]
Bear with me as this is asking to change a few things...

I was trying to review/use the `Selection` and `Solutions` code to become familiar with what's under the hood.  There are some core things that don't appear to work, but could probably be something I'm overlooking (as usual :smile:).

For example, `VS.Solutions.GetActiveProjectAsync()` will return `null` even when I have a project added/opened/selected.  I believe the reason is because it is really a `SolutionItem` and the result comes from using the `as Project` when returning.

I've also found it a little confusing when using `Selection` and `Solutions` as they both are related to getting items from the solution (for the most part).  Plus, there is some overlap.  For example, `VS.Selection.GetSelectedItemsAsync()` and `VS.Solutions.GetActiveSolutionItemAsync()` both call `VS.Selection.GetSelectedHierarchiesAsync()` under the hood.

In addition, the wording for `Selection` seems too open-ended as you could eventually have selections for other things other than the solution.  

I've not had a chance to learn more about the Events (Selection and Solution), but they also appear to have some common pieces (like `SelectionChangedEventArgs` which use `SolutionItem`).

With that, I recommend we consolidate with the initial changes below.  This wouldn't change logic functionality at first, but help simplify/prepare to address some of the broken areas (like `GetActiveProjectAsync()` mentioned above).

- [ ] Rename (current) `Solution.cs` to `SolutionRoot.cs` as it is a `SolutionItem`
- [ ] Rename `Solutions.cs` to `Solution.cs`
- [ ] Move `Selection.cs` code to `Solution.cs`
- [ ] Deprecate `Selection.cs` file
- [ ] Consolidate `SelectionEvents.cs` to `SolutionEvents.cs` or at least move `SelectionEvents.cs` under Solution folder for now.
- [ ] Other?

I started a possible PR, but since this is asking for fundamental changes, I wanted to get feedback before attempting.  Hopefully this make sense.  Thoughts?

**Comment by bluetarpmedia** [comment]
Yeah, I think some refactoring would be helpful.

I think `VS.Services.GetSolutionAsync()` should be renamed to `VS.Services.GetSolutionServiceAsync`. I realise the prefix `VS.Services` may already imply that, but I think it currently can be interpreted as "Here's a service which returns the current solution".

What do you think about `SolutionTools` and `CurrentSolution`?

`Solutions.cs` -> `SolutionTools.cs`
`Solution.cs` -> `CurrentSolution.cs`

**Comment by madskristensen** [comment]
I've got the same thoughts but haven't had time to reason about it yet.

There is a difference between selection and solution in that what's selected isn't always part of the solution. So there isn't any `IVsHierarchy` for it. To consolidate the concepts, we need to take that into account somehow. Also, I want to add support for Open Folder so you can get the selected file/folder names, but they are not SolutionItems. 

To take this a step further, 'Documents.cs' and `DocumentView` are also closely related to both `Selection` and `Solution` though represents a different state - they are open in the editor.

I'm struggling to reason about these distinct yet very similar concepts and how to optimally expose them in the API. Keep the ideas coming, this is something we should fix before GA

**Comment by shaggygi** [comment]
This is probably a case where I should have added to Discussions instead of creating this issue.  After comments above and getting deeper into the toolkit, there probably should be a few separate high-level discussions added regarding sections of the API/design.  I'm trying to collect some notes from this thread and I'll attempt to add to Discussions in the near future.  I'll probably close this soon after as there will most likely be other issues created from said discussions.

**Comment by madskristensen** [comment]
I'm gonna take a stab at this

**Comment by madskristensen** [comment]
This was done a while ago. There is still a Selection class, but it does other things
