### ISSUE TITLE
How to get the OnBeforeOpenSolution event for the first solution that is opened

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#134]
I have a package that inherits from AsyncPackage
with 
`[PackageRegistration(UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]`

Which UI context do I need to set to make sure that my packages gets loaded **before** the fist solution is loaded so I can register the OnBeforeOpenSolution event in time to see the event for the first solution that is opened.
I am registering the event from a method that gets called from InitializeAsync() like this:
`VS.Events.SolutionEvents.OnBeforeOpenSolution += SolutionEvents_OnBeforeOpenSolution;`
I tried all kind of contexts such as 
- VSConstants.UICONTEXT.SolutionExists_string
- VSConstants.UICONTEXT.EmptySolution_string
- VSConstants.UICONTEXT.ShellInitialized_string

but nothing seems to work .
I have 2 packages
1. A project system for a custom language
2. A language service for a custom language

The project system seems to be initialized first (which makes sense because the project file is opened before the source files) but when the first project of our custom language is opened then the solution is already open and the OnBeforeOpenSolution() does not get fired.

**Comment by reduckted** [comment]
Because your extension loads asynchronously, I don't think there's any way to guarantee your extension will load before the solution starts loading. 

Do you need to do something before the solution is opened, or are you just trying to detect when a solution is opened? The usual way of handling that scenario is to check if a solution is already open when your package loads, and call the event handler yourself.

```cs
public async Task InitializeAsync(CancellationToken cancellationToken) {
    VS.Events.SolutionEvents.OnBeforeOpenSolution += SolutionEvents_OnBeforeOpenSolution;

    if ((await VS.Services.GetSolutionAsync()).IsOpen()) {
        SolutionEvents_OnBeforeOpenSolution();
    }
}
```

**Comment by madskristensen** [comment]
@reduckted is right. the official guidance follow that principal and can also be found at the [VSSDK Samples repo](https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/SolutionLoadEvents).

**Comment by RobertvanderHulst** [comment]
Ok guys, this helps.
