### ISSUE TITLE
Lazily initialize elements so that you are not forced to split because of something you are not using?

### ISSUE THREAD

**Issue by jcassidyav** [VsixCommunity/Community.VisualStudio.Toolkit#140]
The scenario I have is that It seems that I do not need to split my extension, the only Issue I have is that I was using the DTE to get the project events.

The solution I thought was that I will use the 16 version of the toolkit for those events and my extension will be compatible with 16 and 17.

However while it is the case that the Build events work fine,  I am seeing it fail in VS17 because of the Events.WindowEvents being Initalized when I access the Events object to get a handle on the BuildEvents.

If the various branches of the hierarchy initalized lazily, i.e. only when they were used, then I would not need to split my extension unless I strayed into the areas that forced a split.

**Comment by madskristensen** [comment]
This has been fixed already, but not yet published to NuGet. You can use the latest CI NuGet feed to get the latest and greatest. See here: https://github.com/madskristensen/ThemeSwitcher/blob/master/nuget.config

**Comment by jcassidyav** [comment]
Mmm I was running against what I built from source it was breaking for me still.

**Comment by madskristensen** [comment]
Oh, can you see where the issue occurs and how it can be fixed?
