### ISSUE TITLE
Some issues after updating to build 76

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#144]
I upgraded from build 75 to build 76 (I am using 15.076.253-pre because my code also needs to work with VS 2017).
I noticed that some of the signatures of the SolutionEvents have changed. That is OK.

However the SolutionEvents.OnBeforeOpenProject no longer exists. Is that an omission, or is that on purpose? 

I also noticed that the OnAfterLoadProject does not get called.

Also when enumerating the projects and their children (folders and files) from the AfterLoadSolution I am getting an E_NOTIMPL exception when enumerating the Children of a Project csproj file.

Finally you have introduced a type "File" the the toolkit. This causes lots of name conflicts with existing code in my project that calls File.Exists(). File.Delete() etc. I have prefixed this code with System.IO now.

But it would have been nice if you would have chosen a more specific name.

**Comment by reduckted** [comment]
Regarding the `File` type, in #143 I've renamed `Folder` to `PhysicalFolder`. If that's accepted, then perhaps renaming `File` to `PhysicalFile` could be a good way to avoid the naming conflicts.

**Comment by RobertvanderHulst** [comment]
@reduckted I second that.

**Comment by madskristensen** [comment]
PhysicalFile sounds good to me
