### ISSUE TITLE
[QUESTION] Moving away from EnvDTE - how to get startup projects

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#154]
I finally realised I can use the library to move away from having any `using EnvDTE;` so I can have a single VSIX for both VS 2019 and 2022 - but there are a few stumbling blocks:

**How to get StartupProjects?**

This is what I currently have

```csharp
            object[] startupProject = (object[])dte.Solution.SolutionBuild.StartupProjects;

            if (startupProject?.Length != 1)
            {
                return null;
            }

            try
            {
                var project = dte.Solution.Item((string)startupProject[0]);

                var path = project.GetOutPutAssemblyPath();

                return path;
            }
            catch
            {
                return null;
            }
```

Related issue: https://github.com/ErikEJ/EFCorePowerTools/issues/1046

**Comment by reduckted** [comment]
A single startup project can be retrieved using the `IVsSolutionBuildManager` service.

```cs
IVsSolutionBuildManager buildManager;
IVsHierarchy startupProject;
Project project;

buildManager = await VS.Services.GetSolutionBuildManagerAsync();
                
ErrorHandler.ThrowOnFailure(buildManager.get_StartupProject(out startupProject));

// Use the IVsHierarchy...
                
// Alternatively, you can create a `Community.VisualStudio.Toolkit.Project` from it:
project = (Project)await SolutionItem.FromHierarchyAsync(startupProject, (uint)VSConstants.VSITEMID.Root);
```

When there's multiple startup projects configured, it seems to use whatever was previously the single startup project, so I don't think it's very reliable. 

For example, you have projects `A`, `B` and `C`. If you set the startup project as `A`, then `IVsSolutionBuildManager` will return `A` as the startup project. If you then set the startup projects to be `B` _and_ `C`, then `IVsSolutionBuildManager` will still return `A` as the startup project.

**Comment by ErikEJ** [comment]
Thanks, works like a charm!
