### ISSUE TITLE
[QUESTION] Moving away from EnvDTE - how to detect debug mode

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#155]
I finally realized I can use the library to move away from having any `using EnvDTE;` so I can have a single VSIX for both VS 2019 and 2022 - but there are a few stumbling blocks:

**How to detect debug mode?**

This is what I currently have

```csharp
                 if (_package.Dte2.Mode == vsIDEMode.vsIDEModeDebug)
                 {
                    EnvDteHelper.ShowError(CompareLocale.CannotCompareContextToDatabaseWhileDebugging);
                    return;
                }
```

Related issue: https://github.com/ErikEJ/EFCorePowerTools/issues/1046

**Comment by reduckted** [comment]
I'm not sure which debugger modes map to the IDE modes, but this seems like it would be the equivalent to what you have above:

```cs
IVsDebugger debugger = await VS.Services.GetDebuggerAsync();

DBGMODE[] mode = new DBGMODE[1];
ErrorHandler.ThrowOnFailure(debugger.GetMode(mode));

if (mode[0] != DBGMODE.DBGMODE_Design)
{
    EnvDteHelper.ShowError(CompareLocale.CannotCompareContextToDatabaseWhileDebugging);
    return;
}
```

https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.dbgmode?view=visualstudiosdk-2019

**Comment by ErikEJ** [comment]
Perfect, thanks!
