### ISSUE TITLE
[BUG] .sqplproj Rebuild does not build

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#158]
Build return OK, but no .dacpac file is built:

            var project = await GetProject(sqlprojPath);
            if (project == null) return null;

            var searchPath = Path.Combine(Path.GetDirectoryName(project.FullPath), "bin");

            var files = Directory.GetFiles(searchPath, "*.dacpac", SearchOption.AllDirectories);

            foreach (var file in files)
            {
                File.Delete(file);
            }

            var buildStartTime = DateTime.Now;

            var ok = await VS.Build.BuildProjectAsync(project, BuildAction.Rebuild);

            if (!ok)
            {
                throw new Exception("Dacpac build failed");
            }

            files = Directory.GetFiles(searchPath, "*.dacpac", SearchOption.AllDirectories);

**Comment by reduckted** [comment]
It _kind of_ works. The problem is (and it is the same for all project types), that `BuildProjectAsync` doesn't wait for the project to finish building before it returns. It returns true if `IVsSolutionBuildManager.StartSimpleUpdateProjectConfiguration` succeeds, but the build is more than likely still occurring at that point.

**Comment by ErikEJ** [comment]
I see! That is why I get error reports like this: https://github.com/ErikEJ/EFCorePowerTools/issues/1121

**Comment by ErikEJ** [comment]
That's not really what I would expect, though

**Comment by reduckted** [comment]
> That's not really what I would expect, though

Indeed! I would expect it to wait for the build to complete before returning.

**Comment by ErikEJ** [comment]
@madskristensen Should this be in the latest CI build? I do not see any improvement...

**Comment by madskristensen** [comment]
This should be in the CI which has the PR made by @reduckted

**Comment by ErikEJ** [comment]
Ok, then I have to open again, because it is not working.
