### ISSUE TITLE
[BUG] BuildProjectAsync does not work

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#174]
Using 16.0.76.288-pre, BuildProjectAsync exits immediately, and does not wait for the build to complete.  

Should it have be named StartProjectBuildAsync ? 😄 

The fix for #158 did not work (or it is not in the latest daily?)

**Comment by reduckted** [comment]
Works fine for me. 

```cs
private async Task ExecuteAsync() {
    await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();

    var output = @"D:\Code\Sandpit\ExtensionTester\source\ExtensionTester\bin\Debug\netcoreapp3.1\ExtensionTester.dll";

    await VS.MessageBox.ShowAsync(
        $"Before build. Output exists = {System.IO.File.Exists(output)}",
        icon: OLEMSGICON.OLEMSGICON_INFO,
        buttons: OLEMSGBUTTON.OLEMSGBUTTON_OK
    );

    var project = await VS.Solutions.GetActiveProjectAsync();
    await VS.Build.BuildProjectAsync(project);

    await VS.MessageBox.ShowAsync(
        $"Build complete. Output exists = {System.IO.File.Exists(output)}",
        icon: OLEMSGICON.OLEMSGICON_INFO,
        buttons: OLEMSGBUTTON.OLEMSGBUTTON_OK
    );
}
```

I've even made MSBuild pause for about 10 seconds.

![build](https://user-images.githubusercontent.com/10321525/135713028-9a26da77-cc46-41d7-9497-7b70d8fd2d83.gif)

**Comment by ErikEJ** [comment]
Let me give it another try, maybe I misunderstood the return value.

**Comment by ErikEJ** [comment]
OK, I am an idiot 🥇 - thanks for this incredibly useful project, it is a life saver!

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/EFCorePowerTools/commit/f35ad68c31cc2a1c1dd5fdd38c08c9a6bd6966a0
