### ISSUE TITLE
[Suggestion] Use Directory.Build.props files to manage build properties

### ISSUE THREAD

**Issue by reduckted** [VsixCommunity/Community.VisualStudio.Toolkit#175]
With more projects being added to the solution, it's getting a bit difficult to determine where the build properties for a project are stored. Using `Directory.Build.props` files is a great convention that will help make it easier to specify build properties for specific types of projects.

You can read more about it here: https://docs.microsoft.com/visualstudio/msbuild/customize-your-build#directorybuildprops-and-directorybuildtargets

In order to really take advantage of `Directory.Build.props` files, we'll need to change the directory structure a bit. This is what I propose:
![image](https://user-images.githubusercontent.com/10321525/135831965-77f75780-70db-4e32-94b9-4b3fe5a5f9b6.png)

`/Directory.Build.props` (the one in the `Solution Items` folder) will define properties that are common to all projects in the solution. This would be things like `Nullable` and `LangVersion`.

`/src/Directory.Build.props` would define properties that are shared by projects that produce NuGet packages. This would be things like `Authors`, `Copyright`, SignAssembly`, etc.

`/src/toolkit/Directory.Build.props` would define properties that only apply to the toolkit projects. Things like `PackageID`, `RootNamespace`, `Reference` items, etc.

`/test/Directory.Build.props` would define properties for test projects.

**Comment by madskristensen** [comment]
This looks great.
