### ISSUE TITLE
Events of IVsRunningDocTableEvents fire many times

### ISSUE THREAD

**Issue by heku** [VsixCommunity/Community.VisualStudio.Toolkit#179]
Hi,

I found in the source, the `DocumentEvents` is implemented based on `IVsRunningDocTableEvents`, from my test, I found the events defined in `DocumentEvents` not working as expected, the root cause is the events of `IVsRunningDocTableEvents` may fire many times for a simple file openning operation. e.g.  openning a file in Visual Sutio 2022 fires events as below:
```
OnAfterFirstDocumentLock
OnAfterFirstDocumentLock
OnAfterAttributeChange
OnBeforeLastDocumentUnlock
OnAfterFirstDocumentLock
OnAfterAttributeChange
OnBeforeLastDocumentUnlock
OnAfterFirstDocumentLock
OnBeforeDocumentWindowShow
OnBeforeDocumentWindowShow
OnBeforeDocumentWindowShow
```

**Comment by RobertvanderHulst** [comment]
These events are documented do be called many times. For example once to get a read lock and when that was succesfully acquired then once to get an edit lock. So this works as expected. 
My changes to the DocumentEvents class yesterday make sure that DocumentEvents.Opened and DocumentEvents.Closed are only called once for each file.

**Comment by heku** [comment]
@RobertvanderHulst thx, lession learned.
