### ISSUE TITLE
NameSpace not found when added as NuGet Package to Solution

### ISSUE THREAD

**Issue by RFBomb** [VsixCommunity/Community.VisualStudio.Toolkit#186]
I discovered this toolkit after getting the core of my extension to work. So I had a bit of the coding done, but I wanted to use this toolkit to add some icing on the cake so-to-speak. 

During my frustration, I had found that this nuget package is not liking my project/solution file at all. The namespace cannot be found. 

Now, interestingly, when I create a new empty project using the extension's custom templates, which also seem to reference the nuget package, this is not an issue at all (I'm able to use `Community.VisualStudio.Toolkit` namespace.) Comparing the csproject files I was able to find no discernable difference betweem them. My theory currently is that the standalone nuget package for this maybe isn't actually including the namespace files, whereas the extension does? I'm not sure, because I'm baffled.

![image](https://user-images.githubusercontent.com/20431767/137822176-cdff5b6a-eba6-4cf1-9a9f-68221848ca6f.png)

Custom template .CSProject Reference:
```
<PackageReference Include="Community.VisualStudio.Toolkit" Version="16.0.76.253-pre" ExcludeAssets="Runtime" />
<PackageReference Include="Microsoft.VSSDK.BuildTools" Version="16.10.1055" />
```

References from the file I imported the nuget package into:
```

<ItemGroup>
    <PackageReference Include="Community.VisualStudio.Toolkit" Version="17.0.76.303" ExcludeAssets="Runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Community.VisualStudio.Toolkit.Analyzers">
      <Version>1.0.76.303</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="16.10.31321.278" ExcludeAssets="runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VSSDK.BuildTools">
      <Version>17.0.5232</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```

Even changing the versions to the same as the template project results in the namespace not found error. So I'm not sure whats up or why the custom project template would be able to use the namespace, but one with the nuget package cant

**Comment by reduckted** [comment]
I've encountered something similar when my extension targeted the wrong framework version. If you're using 16.x of the toolkit, then the target framework of your project needs to be 4.7.2.

**Comment by madskristensen** [comment]
I've created new NuGet packages that contain the major version in the package name. That should fix this

**Comment by RobertvanderHulst** [comment]
Thanks Mads. 
This is VERY much appreciated. Now I will no longer be bothers with 17.* versions for my package that is using 15.*.
