### ISSUE TITLE
[Suggestion] Include the major version number in the package name

### ISSUE THREAD

**Issue by reduckted** [VsixCommunity/Community.VisualStudio.Toolkit#188]
@RobertvanderHulst mentioned this [in another issue](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/186#issuecomment-948048211), and and it's something I had thought about recently too.

All four versions of the toolkit all have the same package ID and only differ based on the major version number. If, for example, you need your extension to be compatible with Visual Studio 2017, then you need to install `v15.x` of the toolkit. But when you do that, you're told that there are updates available to that package because `v17.x` exists. If an update _is_ actually available to the version you have installed (for example, `v15.[x+1]`), then you're unlikely to notice because you would become accustomed to ignoring updates to the toolkit.

This could be prevented by adding the major version number to each package so that we have:
* `Community.VisualStudio.Toolkit.14`
* `Community.VisualStudio.Toolkit.15`
* `Community.VisualStudio.Toolkit.16`
* `Community.VisualStudio.Toolkit.17`

We could also change the package description to specify which version of Visual Studio it's intended for, which would make it easier for people to understand which package they should be using. For example:

![image](https://user-images.githubusercontent.com/10321525/138259261-c80b6048-b664-4e71-9f93-ce5bf8fdcdda.png)

Having a separate package ID for each major version would also allow semantic versioning to be used, which would be nice (@yannduran mentioned the desire for semantic versioning a while ago in https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/25#issuecomment-828105727)

**Comment by ErikEJ** [comment]
This would solve a lot of confusion.

Same thing should be done for the SDK meta package
