### ISSUE TITLE
Should SolutionItem.Name be read-only?

### ISSUE THREAD

**Issue by reduckted** [VsixCommunity/Community.VisualStudio.Toolkit#198]
The `Name` property of `SolutionItem` is read-write, but setting it has no effect on the underlying `IVsHierarchy` that the  `SolutionItem` wraps. Should this property be read-only instead?

`FullPath` has the same issue.

https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/e5230bb3766367e8cccab6f3e3471ec63d7ea4df/src/toolkit/Community.VisualStudio.Toolkit.Shared/Solution/SolutionItem.cs#L41-L49

**Comment by reduckted** [comment]
`Name` could possibly just wrap `_item.Text`, since that's what it's initialized from.

```cs
public string Name => _item.Name;
```

**Comment by madskristensen** [comment]
That makes sense
