### ISSUE TITLE
Update project type guids to be more complete/accurate

### ISSUE THREAD

**Issue by StevenRasmussen** [VsixCommunity/Community.VisualStudio.Toolkit#20]
The [project type guid constants](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/master/src/Community.VisualStudio.Toolkit.Shared/Helpers/ProjectTypes.cs) are a great start.  I think some of them might be slightly off on their meaning (for example, the guid associated with the `WAP` constant is really just a `C#` project) and there are a ton more that can be added that I saw [here](https://www.codeproject.com/Reference/720512/List-of-Visual-Studio-Project-Type-GUIDs).

I can open a PR if it's deemed useful to add them.

**Comment by yannduran** [comment]
I agree with you Steven! I think it should be as complete.accurate as possible.
