### ISSUE TITLE
Active Configuration Changed event ?

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#204]
Does anybody know if there is an event that we can subscribe to, to get notified when the user switch to another configuration and or platform ?

**Comment by reduckted** [comment]
I haven't tried it, but it sounds like [`IVsUpdateSolutionEvents4`](https://docs.microsoft.com/dotnet/api/microsoft.visualstudio.shell.interop.ivsupdatesolutionevents4) is what you're after.

**Comment by RobertvanderHulst** [comment]
There is already an event in the toolkit but it does nothing (in the BuildEvents class(👍🏼 
```
        int IVsUpdateSolutionEvents.OnActiveProjectCfgChange(IVsHierarchy pIVsHierarchy) => VSConstants.S_OK;
        int IVsUpdateSolutionEvents2.OnActiveProjectCfgChange(IVsHierarchy pIVsHierarchy) => VSConstants.S_OK;
```
I'll try to implement that and will send a pull request

Robert
