### ISSUE TITLE
Newtonsoft version number check and VS 2017

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#207]
The max newtonsoft version number for VS 2017 in the file Constants.15.props  is now set to 8.0.3.
However according to the following page

https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/

for recent versions of VS2017 this should be 9.0.1.

If you reference a package such as Microsoft.VisualStudio.Language version 15.8.525 then this will link the newtonsoft version 9.0.1 which causes a build warning.

Some questions:
- Can the warning be suppressed
- Or should we update the version to match the more recent VS2017 versions
- Or can I override the setting in the project file?
- I am also including this package in a project file for another (our own) development language. This uses packages.config and not a packagereference
- I am seeing the warning
`warning CVSTBLD002: The version of Newtonsoft.Json cannot be greater than 8.0.3, but version  is currently being used.`

As you can the warning does not pick up the current version. What could be causing this ?

**Comment by reduckted** [comment]
> Can the warning be suppressed

Yes, you can add this to the project file:
```xml
<PropertyGroup>
    <NoWarn>$(NoWarn);CVSTBLD002</NoWarn>
</PropertyGroup>
```

> Or should we update the version to match the more recent VS2017 versions

The 15.0 toolkit package references the 15.0 version of the Visual Studio SDK, so I don't think we require anything above 8.0.3.

https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/f561cc80d69ec8a177c9eecbbbb751cfebf0d9f7/src/toolkit/Community.VisualStudio.Toolkit.15.0/Community.VisualStudio.Toolkit.15.0.csproj#L10

> Or can I override the setting in the project file?

Although it wasn't intended to be overridden, the version is just defined as a build property, so you can override it:

```xml
<PropertyGroup>
    <CVST_NewtonsoftJsonMaxVersion>9.0.1</CVST_NewtonsoftJsonMaxVersion>
</PropertyGroup>
 ```

> As you can the warning does not pick up the current version. What could be causing this ?

The version check currently only works with `PackageReference`-style references (see the _Limitations_ section in #195). 

Is there any chance that you could [migrate to PackageReference](https://devblogs.microsoft.com/nuget/migrate-packages-config-to-package-reference/)

**Comment by RobertvanderHulst** [comment]
@reduckted 

> The 15.0 toolkit package references the 15.0 version of the Visual Studio SDK, so I don't think we require anything above 8.0.3.

We require a more recent revision for VS 2017 so we can support asynchronous operations in our language service that did not exist in 15.0

> Although it wasn't intended to be overridden, the version is just defined as a build property, so you can override it:

I have done that and this indeed suppresses the warning.

> Is there any chance that you could migrate to PackageReference

No, not at this moment. The component that shows this warning is written in XSharp (X#) our own development language.
For our project system we have used MPF. Until recent we were also supporting VS 2015 which does not know PackageReferences. And MPF never added support for PackageReference.

We are working on updates for the project system and we will add support for both SDK style projects and PackageReferences.
My work with the Toolkit is part of this.

Rober
