### ISSUE TITLE
ProjectTypes.CSHARP GUID is incorrect

### ISSUE THREAD

**Issue by RFBomb** [VsixCommunity/Community.VisualStudio.Toolkit#221]
I Believe C# GUID is incorrect. I can submit a PR if you want me to.

This is my use case:
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators?view=vs-2022

I pulled the working GUID from their example.

This code fails to register my SingleFileGenerator for use:
`[CodeGeneratorRegistration(typeof(XSDCustomTool), "XSDCustomTool", ProjectTypes.CSHARP, GeneratesDesignTimeSource = true)]`

This code registers succesfully:
`[CodeGeneratorRegistration(typeof(XSDCustomTool), "XSDCustomTool", "{FAE04EC1-301F-11D3-BF4B-00C04F79EFBC}", GeneratesDesignTimeSource = true)]`

also, the constants `WINDOWS_CSHARP ` and `CSHARP ` are identical.

Not Working:__ "{FAE04EC**0**-301F-11D3-BF4B-00C04F79EFBC}"
Working:______  "{FAE04EC**1**-301F-11D3-BF4B-00C04F79EFBC}"

As for VB, I didn't see the example GUID from MS listed at all on in the ProjectTypes files.
`"{164b10b9-b200-11d0-8c61-00a0c91e29d5}"`

To me, this suggests that these GUIDs differ somehow from where the "ProjectTypes" guids were gotten from. Maybe these should have their own static class?

edit:
Here are the registry keys I got from looking at my registry for a VS2019 install, inside of 
`HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\10.0_Config\Generators`

VB -> {164B10B9-B200-11D0-8C61-00A0C91E29D5}
J# -> {e6fdf8b0-f3d1-11d4-8576-0002a516ece8}
C# -> {FAE04EC1-301F-11D3-BF4B-00C04F79EFBC}
LinqToSQL -> {39C9C826-8EF8-4079-8C95-428F5B1C323F}
Unknown -> {349C5850-65DF-11DA-9384-00065B846F21}

**Comment by madskristensen** [comment]
Yeah, the C# guid might be incorrect as you point out. Let's fix it

**Comment by RFBomb** [comment]
I was digging through my registry and searching for other GUIDs that SingleFileGenerators will use. I had edited my original post just as you were commenting, so unsure if you saw it. 

My SFG also needs JS, but I was unable to locate the GUID for that. (I relied on MSDataSetGenerator to discover which guid was what language, since MS put a nice note about which language it is for when they registered it)

**Comment by StevenRasmussen** [comment]
The current C# GUID is working for me (and I've been using it in an extension for many many years now)... so I'm not sure what the difference could be.  In my case I use it to dynamically determine the project type when looking at the `EnvDTE.Project.Kind` property.  I haven't used it in the `CodeGeneratorRegistration` attribute though.  It seems weird that there would be a difference there.  Thoughts?

![image](https://user-images.githubusercontent.com/11198735/141840781-f2ad67d6-2d96-4674-9e32-9f6bd1e7d5e6.png)

**Comment by RFBomb** [comment]
I did more investigating (read: googling) and found that they are in fact different for some reason. I created a new PR that added in a new file to resolve this discrepancy and avoid confusion for people doing something similar.
