### ISSUE TITLE
Readme doc issues

### ISSUE THREAD

**Issue by CoolDadTx** [VsixCommunity/Community.VisualStudio.Toolkit#225]
A couple of issues with the readme for the repo.

1) The section on how to find services says 'for example to.... do the following:` and then there is no code example. I believe that sample code was moved to an earlier section of the readme.
2) The last section mentions the `Extensiblity Toolkit` but the link takes you to a version that only works with VS 2019. It would be nice if the docs mentioned the version(s) that it supports and, most importantly, it was updated to work with VS 2022.

**Comment by StevenRasmussen** [comment]
PR's are very welcome and @madskristensen usually merges them quicker than it takes to eat your lunch 😆.  He's very responsive to say the least... which is a great thing 😉

**Comment by MariaSolOs** [comment]
It seems like this issue can be closed now...?
