### ISSUE TITLE
How to get the language of a PhysicalFile?

### ISSUE THREAD

**Issue by mcleary** [VsixCommunity/Community.VisualStudio.Toolkit#228]
Maybe this is an obvious thing but I'm using this toolkit for the first time. It is obviously much easier to traverse the hierarchy of solution items using this but I still couldn't find a way to get the language associated with a `PhysicalFile`. Of course one can check the file extension but is that how it is supposed to be done?

When using `EnvDTE` this works file because a `ProjectItem` has a `FileCodeModel`. 

```cs
EnvDTE.ProjectItem item = ...;
if (item.FileCodeModel.Language == CodeModelLanguageConstants.vsCMLanguageVC)
{
   // This is a c++ file
}
```

Is there anything similar in this toolkit?

Also, is there a short version of the differences between `Microsoft.VisualStudio.Interop` and `Microsoft.VisualStudio.Shell.Interop`? I'm quite confused about these namespaces

**Comment by madskristensen** [comment]
There is no code model properties on `PhysicalFile`, but we should add it to the toolkit.

**Comment by mcleary** [comment]
That's amazing. How often is the toolkit officially update though visual studio?

**Comment by madskristensen** [comment]
The toolkit is updated through NuGet on no particular schedule. You can always get the CI feed and use that in your project so you don't have to wait for a new official NuGet package to be published. See the Readme.md on how to use the CI feed
