### ISSUE TITLE
Suggested change to SamewordHighlighter

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#259]
Mads,
Most of the implementation in the SameWordHighlighter is now private.
Is it OK with you if I make some of the code protected and virtual, so it can be adjusted in the base class.
For example: our development language is case insensitive, so it would make sense to do case insensitive searches instead of case sensitive. And I would also like to suppress word highlighting for keywords.
Of course I can create a complete own class, but I think it would be a valuable addition if this can be customized in the subclass.

**Comment by madskristensen** [comment]
Absolutely. In fact, perhaps it should also be case sensitive by default

**Comment by RobertvanderHulst** [comment]
Mads,
Thanks. I will make some changes and send you a pull request.
I am thinking of :
- add a public property to control the Find Options
- add a method that you can override to decide if the search is needed (which will return FALSE for keywords in our language)
- add a method that receives the results of _textSearchService!.FindAll(findData) so it can filter out unwanted results (like words in comment regions)
