### ISSUE TITLE
Document events are called twice

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#269]
The DocumentEvents.Closed  and DocumentEvents.Opened are called twice.
The implementation in the toolkit responds to the IVsRunningDocTableEvents.OnAfterFirstDocumentLock and IVsRunningDocTableEvents.OnBeforeLastDocumentUnlock events and according to the docs these events are called once for a ReadLock and once for an EditLock

Is it OK if I change the implementation and for example only call the events when the ReadLock changes ?

**Comment by madskristensen** [comment]
Yes please. Great catch!!

**Comment by reduckted** [comment]
This might fix #179.
