### ISSUE TITLE
boolean options seems to default to "false"

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#280]
Adopting BaseOptionPage, all boolean values seems to default to false, and this is no desired.

```
        [Category("Other"),
        DisplayName(@"Participate in Telemetry"),
        Description("Help improve the EF Core Power Tools by providing anynonymous usage data and crash reports"),
        DefaultValue(true)]
        public bool ParticipateInTelemetry { get; set; }
```

![image](https://user-images.githubusercontent.com/4169187/150787382-fa09d79f-ac55-415c-929f-a59a197050b4.png)

**Comment by StevenBonePgh** [comment]
Think of it like a [Winforms control](https://stackoverflow.com/questions/2329868/net-defaultvalue-attribute):
- Like Category, DisplayName, and Description attributes, the `DefaultValueAttribute` is a hint for the editor to render the setting as bold/not bold based on the current value and the attribute's value. 
- However, the actual default is what the object looks like after the constructor completes. 
 
The toolkit's behavior is that after the settings object is constructed, it looks for the persisted setting and sets the property only if the persisted setting was found. 

Therefore if you want a default that is not the type's default, you need to explicitly set it via ctor or property initializer:
```
        [DefaultValue(true)]
        public bool ParticipateInTelemetry { get; set; } = true;
```

Not sure what you mean by 'porting existing options'. If these settings are already in the Settings Store, and you are migrating to the toolkit there are attributes that allow you to modify the default behavior as to where each setting lives and how it is serialized to the underlying type. See the [*Attributes and the enumerations SettingDataType and NativeSettingsType](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/tree/master/src/toolkit/Community.VisualStudio.Toolkit.Shared/Options)

**Comment by ErikEJ** [comment]
Great, see it now - https://github.com/madskristensen/MarkdownEditor2022/blob/master/src/Options/AdvancedOptions.cs#L19
