### ISSUE TITLE
Cant get Community.VisualStudio.Toolkit.17 reference to resolve in a shared project

### ISSUE THREAD

**Issue by xEsteem** [VsixCommunity/Community.VisualStudio.Toolkit#289]
I have a visual studio extension that currently has a 2017 and a 2019 version, and a shared project they both use which contains almost all of the commands and additional logic. the 2017 version uses toolkit.15, and the 2019 version uses toolkit.16, and it all works fine.

More recently ive created a new project, a 2022 version, and in that i have installed the toolkit.17 version, but my project cannot build, because in the shared project of my references to the toolkit classes to not resolve.
`<PackageReference Include="Community.VisualStudio.Toolkit.17" Version="17.0.394" />`
The package is being restored properly and exists in my .nuget folder. And in fact, if i change the reference from a nuget package reference to an explicit dll reference, and reference the dll directly from **.nuget\packages\community.visualstudio.toolkit.17** it works. But i cant get it to work while added to my project as a package reference. Any ideas? 

i followed the documentation here https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by ErikEJ** [comment]
Target framework too low? Must be 4.8 I think.

**Comment by xEsteem** [comment]
oh dear, yea that was the issue.. sorry, was on 4.7.2, same as my 2017 and 2019 versions!
Thanks!
