### ISSUE TITLE
Updates to NuGet packages

### ISSUE THREAD

**Issue by StevenRasmussen** [VsixCommunity/Community.VisualStudio.Toolkit#290]
@madskristensen - Not a rush... just wondering how often you push updates to the NuGet packages?  I'm waiting for the changes in one of the PR's ([#277](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/pull/277)) that was merged this last week to get pushed to the NuGet packages so that I am able to take advantage of them in the `Community.VisualStudio.Toolkit.DependencyInjection` project.  This is with regards to auto-registering commands and having constructors in those commands that can take any parameters and are injected by the DI container. Thanks!

**Comment by madskristensen** [comment]
There's not particular cadence, but I encourage you to use the CI feed if you are blocked. I do that for several of my extensions

**Comment by StevenRasmussen** [comment]
Ah... should've thought of that. Thanks!
