### ISSUE TITLE
saving the VSCommandTable.vstc prompts for line endings

### ISSUE THREAD

**Issue by AdmiralSnyder** [VsixCommunity/Community.VisualStudio.Toolkit#293]
hi, i created a community vsix project "My Company". whenever i save the VSCommandTable.vstc file, i get this message:
![image](https://user-images.githubusercontent.com/16213022/152459763-2aa49603-7800-49b4-bfd8-708a31dfe93e.png)
from the vsctcompiler - with the result that a couple of line endings are damaged. is this a problem on my side or with the VSTC compiler?

**Comment by reduckted** [comment]
This sounds like an issue with the [VsixSynchronizer](https://github.com/madskristensen/VsixSynchronizer) extension.

**Comment by AdmiralSnyder** [comment]
thanks. i created https://github.com/madskristensen/VsixSynchronizer/issues/16
