### ISSUE TITLE
Visual Studio crashes when calling Commands.ExecuteAsync

### ISSUE THREAD

**Issue by niemyjski** [VsixCommunity/Community.VisualStudio.Toolkit#319]
I have been noticing hard crashes with the toolkit (all recent versions) with the latest version of VS 2022 (17.1.3) when executing ExecAsyncs. I have a simple command that calls into a sync command service (this command service is also invoked from many other areas including WPF event handlers (and it's bad it's async over sync...). I've been unable to capture stack traces as it force closes visual studio even when you have break on all exceptions.

```cs
   [Command(PackageGuids.guidUICONTEXTMyFileSelectedCmdSetString, PackageIds.GenerateOutputsCommand)]
    public sealed class GenerateOutputsCommand : GenerateOutputsMenuCommandHandler<GenerateOutputsCommand> {
        protected override Task ExecuteAsync(OleMenuCmdEventArgs e) {
            _outputWindowService.Show();
            return Task.CompletedTask;
        }
    }
```

```cs
public async void Show() {
            try {
                await VS.Commands.ExecuteAsync("View.Output", String.Empty);
            } catch (Exception ex) {
               // log crash...
            }
        }
```

**Comment by madskristensen** [comment]
What happens if you instead of calling `await` on it, instead calls `.FireAndForget();`?

You can also get to the output window using `VS.Windows...`

**Comment by niemyjski** [comment]
It still crashes the process with `FireAndForget()`. I can't use VS.Windows... because it doesn't focus / show the output window. For context, I have our own output pane, but I don't know what the user selected pane was, nor if the window is hidden inside of a dock, or not there. View.Output just displays it which is exactly what I want in this context. I've tried a lot of things with VS.Windows and the pane activation and none of it works how I want it to.

**Comment by reduckted** [comment]
Is there anything in the `ActivityLog.xml` file? I can't remember where it is usually saved to, but I think it's either `%APPDATA%/Microsoft/VisualStudio/17.0_abcdef` or `%LOCALAPPDATA%/Microsoft/VisualStudio/17.0_abcdef`.

If it's the experimental instance that's crashing, then the `17.0_abcdef` will be `17.0_abcdefExp` instead.

The .NET runtime usually logs hard crashes in the _Application_ event log as well. There might be something logged there with a stack trace.

**Comment by niemyjski** [comment]
I've been seeing this for the last 2.5 weeks and I ran Windows Updates yesterday for both Windows 11 and .NET framework updates and now I'm not seeing this behavior. If something changes, or I'm able to reproduce with logs I will reopen this issue. I really wonder what update or change would have caused this as it was super reliable to reproduce previously.
