### ISSUE TITLE
Getting (non-blocking) warning on publish

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#327]
I have an extension that use Community Toolkit 16, but targets but VS 16 and VS 17.

I am now getting this warning on publish:

https://docs.microsoft.com/en-us/visualstudio/extensibility/vssdk-messages/vsixcompatibility1001

How do I keep a single market place entry and solve this?

**Comment by ErikEJ** [comment]
I get this via email after publish (no warnings ??):

Extension validation is complete for your extension [EF Core Power Tools (ErikEJ.EFCorePowerTools)](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools). No issues were observed and the version 2.5.958 is available for use in Visual Studio Marketplace.

**Comment by ErikEJ** [comment]
Anyone?

**Comment by reduckted** [comment]
Both Bing and Google given me exactly three results for that error code - one is the English documentation, one is the Czech documentation, and the other is this GitHub issue. 😆

My (probably incorrect) understanding was that you could always use the latest VSSDK build tools package, regardless of which SDK package you used. Perhaps that has changed in the latest version of the VSSDK package?

Maybe you could ping [the authors](https://github.com/MicrosoftDocs/visualstudio-docs/commits/main/docs/extensibility/vssdk-messages/vsixcompatibility1001.md) of that documentation?

**Comment by ErikEJ** [comment]
Great, I will try that

**Comment by ErikEJ** [comment]
@ankitvarmait I see you are the author of the docs mentioned above.

I have an [extension](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/EFCorePowerTools/source.extension.vsixmanifest) that targets both VS 2019 and VS 2022 (in order to have a single market place entry mainly). 

When publishing via the marketplace portal I get the warning above, and I wonder if there is any way to avoid it. (Currently it is luckily non-blocking)

Having the ability to publish multiple vsix packages for the same marketplace ID would solve this, I guess?

**Comment by madskristensen** [comment]
@ErikEJ a related issue is tracked here: https://developercommunity.visualstudio.com/t/Unable-to-publish-to-marketplace---VsixP/10011817
