### ISSUE TITLE
ToolWindows: Ability to use Site services like IVsTrackSelectionEx

### ISSUE THREAD

**Issue by niemyjski** [VsixCommunity/Community.VisualStudio.Toolkit#335]
I migrated over from VSXtra to this toolkit, and I noticed during testing that my BaseToolWindow doesn't allow me to consume sited services like IVsTrackSelectionEx. The old ToolWindow implementation was based on WindowPane and thus allows me to use cited services.

My use case is that I have a tool window control and I want to set the property window selection to reflect a selected tool window item.

```cs
var trackSelection = Package.GetService<SVsTrackSelectionEx, IVsTrackSelectionEx>();

string browser = typeof(CustomPropertyBrowser).GUID.ToString("B");
trackSelection.OnElementValueChange((uint)VSConstants.VSSELELEMID.SEID_PropertyBrowserSID, 0, browser);
```

**Comment by reduckted** [comment]
Where would you normally get the `IVsTrackSelectionEx` service from? The `ToolWindowPane` object? I just tried getting it from there and it threw an error saying that the service wasn't available. I haven't tried getting services like that before, so maybe I'm doing something wrong. Do you have an example of what you used to do?

**Comment by niemyjski** [comment]
Our toolwindow used to implement (https://github.com/niemyjski/VSXtra/blob/master/VSXTra/Runtime/VSXTra/Windows/WindowPanes/ToolWindowPane.cs#L92) and then it would call (https://github.com/niemyjski/VSXtra/blob/master/VSXTra/Runtime/VSXTra/Windows/WindowPanes/WindowPane.cs#L529) which is sited.

@reduckted some services can only be called in a specific scopes (sited)

**Comment by reduckted** [comment]
Ah ha! I was calling `GetService` as soon as the `ToolkitPackage` had created the tool window, but at that point `IVsWidnowPane.SetSite` had not been called, hence why it was throwing an error saying that the service wasn't available.

My first thought was to provide a way to pass the `ToolWindowPane` into the `BaseToolWindow` implementation and/or the `FrameworkElement` that is the pane's content. That's simple enough to achieve with an interface like this:

```cs
public interface IToolWindowPaneAware {
    void SetPane(ToolWindowPane pane);
}
```

If the pane's content implements that interface, then the `ToolkitPackage` can call that method after the pane has been created. The only problem with that is you run into the problem that I had - when the pane is given to the content, it hasn't been initialized (and you therefore can't get sited services from it), and there's no way to know _when_ it will be initialized.

So, to overcome that problem we can require the pane to inherit from a special `ToolWindowPane` implementation that allows us to know if it has been initialized, and then only call `IToolWindowPaneAware.SetPane` once the pane has been initialized.

I've implemented this solution here: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/compare/master...reduckted:feature/tool-window-pane-aware

I've changed the `RunnerWindow` to implement the `IToolWindowPaneAware` interface as an example. If you need your `ToolWindowBase` implementation to get access to the pane, then you just need to override the `SetPane` method.

Do you think that would work for your scenario? If it sounds OK, I'll turn it into a pull request.

**Comment by niemyjski** [comment]
@reducked Yes, I think that will work!

**Comment by niemyjski** [comment]
Thanks again for the PR and help! Just wanted to provide an update that this fix is working great!! Just a reminder to anyone reading. If you need to get the sited service, you need to call `pane.GetService`.
