### ISSUE TITLE
Please change the name `ForgetAndLogOnFailure` to `FireAndForget`

### ISSUE THREAD

**Issue by yannduran** [VsixCommunity/Community.VisualStudio.Toolkit#36]
Please rename  `ForgetAndLogOnFailure()` back to `FireAndForget()` as it was the simplest and most elegant name for the method. 

For a toolkit that's aiming to **simplify** and make writing extensions **easier**, a name like `ForgetAndLogOnFailureviolates` violates those base tenets IMO. The original name `FireAndForget` should have been kept, with a `logOnFailure` parameter added as @reducted suggested, as this makes the most sense and caters to developers who are new to writing extensions as well as users with more advanced logging requirements.

Can we PLEASE just go back to `FireAndForget`? It's in a bunch of YouTube videos, and `ForgetAndLogOnFailure ()` will only confuse/annoy people.

>Mads: _It was @AArnott that suggested renaming it to more accurately reflect what the method was doing. It's not just "forgetting" a task, it handles the errors and logs to the output window. I like the idea of adding an optional parameter that allows you to disable the output window logging. **I'm personally OK with the name FireAndForget()**, but there are various opinions on this. Perhaps we can come up with a list of names to choose from_

>Yann: _With all due respect to Andrew, just because he suggested renaming it doesn't mean it has to be renamed. Andrew works with very technical details, so yes, he would think that way. It's great that Andrew's on board to do code reviews, to point out any technical flaws in our code, or any bad practices, but overly complicating names just to cover everything a method does is not what I thought this toolkit was about._
>
>We're creating a Community Toolkit to make writing extensions easier. Nobody really needs to know the technical details behind that particular method. Users just need to know that they can use it to fire an async method and forget about it (and the technical details are handled for them under the hood). That's what we've been trying to do, abstract the technical/difficult-to-know-about details under a simplified facade. The analyzers can direct people to use this method instead of the others, and can give a small explanation about the logging option at the same time. It's simple and elegant. Your first instinct was a good one!
>
>For more advanced users, the addition of the parameter allows control of the logging, if required - without confusing users who don't care about logging any errors.
>
>I am also (obviously) fine with using `FireAndForget()`. And as you may have possibly guessed, I feel VERY strongly about this._

**Comment by yannduran** [comment]
Thanks for that clarification Andrew.  I'm the same, I also prefer **_discoverable and simple over precisely accurate_**. What I don't want to see happen in this toolkit is awkwardly-named methods like some of the very methods that we're trying to make easier to use.

**Comment by yannduran** [comment]
@AArnott I hope you didn't think I was having a go at you, that wasn't my intention at all.

**Comment by madskristensen** [comment]
Let's make a decision and close on this. We've heard arguments for renaming to `FireAndForget` and for keeping it `ForgetAndLogOnFailure`. A third option is to name it something different and let it take an optional boolean parameter to opt in/out of logging (this is true for the `FireAndForget` option too).

I personally like to add an optional parameter to opt out of logging. To me, that eliminate the name `ForgetAndLogOnFailure` and a different name must be found.

Here are some suggestions:

* `FireAndForget`
* `Start`
* `Fire`
* `Forget` (this conflicts with extension method in the Threading library, but may not matter given the boolean parameter)

Thouhts?

**Comment by bluetarpmedia** [comment]
My vote would be for `FireAndForget(bool logOnFailure = true)`.

I'd suggest ruling out `Forget` for simplicity - it'd be nice to read the code without having to examine the using directives to see which method it is.

With optional params, it'd be good to ensure we can still add overloads in the future if needed. For example, it might be nice to pass an object that implements an interface so that the client extension can control logging itself (such as to an exception monitoring service like Raygun, Sentry, Application Insights).

```
interface IExceptionLogger
{
    void Log(Exception ex);
}

// Couldn't have both:
FireAndForget(bool logOnFailure = true);
FireAndForget(IExceptionLogger logger = null);
```

Obviously in that case we'd probably do:

`FireAndForget(bool logOnFailure = true, IExceptionLogger logger = null)`

But I just mean it as an example of potentially impacting a future overload.

**Comment by reduckted** [comment]
Using an "options" object would probably be a better option for future extensibility. Something like this:

```cs
void FireAndForget(FireAndForgetOptions? options = nullI);

class FireAndForgetOptions {
    static FireAndForgetOptions Default = new FireAndForgetOptions { LogOnFailure = true };

    bool LogOnFailure { get; init; }
    IExceptionLogger ExceptionLogger { get; init; }
}

**Comment by yannduran** [comment]
I'm happy with the suggestions that @bluetarpmedia and @reduckted have made.

I see no reason that all scenarios couldn't be handled perhaps in one method:

 `FireAndForget(bool logOnFailure = true,  IExceptionLogger logger = null, IFireAndForgetOptions options = null)`

Simple when it needs to be (by default), but able to cater to more advanced scenarios as needed. As well as being future-proofed

**Comment by madskristensen** [comment]
We can do an overload once/if it becomes relevant to add a more complex options object. Let's keep it simple for now. I'll make the changes. Thanks everybody for your input

**Comment by yannduran** [comment]
Sounds great!
