### ISSUE TITLE
Highlighting 1 character identifiers

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#375]
Mads,

In https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/master/src/toolkit/Community.VisualStudio.Toolkit.Shared/MEF/SameWordHighlighterBase.cs#L123
you are checking to see if the highlighted word has a length > 1.

What is the reason for that ?

The current implementation does not highlight single character identifiers, like the often used for loop counters i, j, k 
Are you trying to avoid highlighting braces etc,?

**Comment by madskristensen** [comment]
That looks like a mistake. It should check for a value of 0 instead of 1
