### ISSUE TITLE
AssemblyInfo from community toolkit leaking into consuming extension code analysis

### ISSUE THREAD

**Issue by xEsteem** [VsixCommunity/Community.VisualStudio.Toolkit#382]
This is a strange one, I understand, but I have an analyser and a ruleset that i am using in my code and for one particular rule its specifically expecting a copyright header at the top of the page. For some reason my build is failing because of the `assemblyinfo.cs` from the community toolkit nuget package, which has an invalid header. I don't understand why this is leaking within the scope of my project's code analysers.

The problem file is
`C:\Users\**username**\.nuget\packages\community.visualstudio.toolkit.17\17.0.339\build\AssemblyInfo.cs`

I also don't know how to suppress this issue externally in my code, without suppressing it for my entire extension. I couldnt get a [suppressmessage attribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute?view=net-6.0) working in my own assemblyinfo.cs that targetted specifically that file or that package reference without suppressing it in my own code too.

Any help would be greatly appreciated.

For completeness the analyzer is StyleCop.Analyzers and the rule is SA1633:File should have header.

For reasons out of my control, I cant stop using stylecop, i cant demote it to a warning, and ideally i dont want to have to suppress this rule in the extension project itself.

**Comment by madskristensen** [comment]
It's there to ensure that the running extension can always resolve the toolkit dll. It's needed.

If you know how to suppress the analyzer warning in code, please add it to the assemblyinfo.cs here: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/master/demo/VSSDK.TestExtension/Properties/AssemblyInfo.cs

**Comment by reduckted** [comment]
Analyzers will automatically skip generated code. If we mark the file as being generated code, then that should fix this problem.

From memory, a file can be marked as generated by adding this comment as the first thing in the file.

```cs
// <auto-generated /> 
```

**Comment by xEsteem** [comment]
Yes I can suppress the issue in my OWN extension by adding something like
```
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Community Visual Studio Toolkit AssemblyInfo breaks this rule.")]
```
but as I say that suppresses it in my entire extension which is undesirable.
I appreciate that this file is needed but its strange that its leaking into my code analysis. 

Adding `// <auto-generated />` to the top of that file _would_ resolve the issue (just tried editing it locally and it was fine) but whether or not you want to add that then thats up to you guys i suppose.
If not i'll try and find some way of skipping it only on that one file my end (which i havent been able to do yet)
