### ISSUE TITLE
RichTextBox does not work with UseVsTheme

### ISSUE THREAD

**Issue by scottcantwell** [VsixCommunity/Community.VisualStudio.Toolkit#386]
![image](https://user-images.githubusercontent.com/90006729/200740098-12e15097-0cdb-4801-b3f1-68ffda239106.png)

Textcolor is black instead of white when using a RichTextBox in Dark Color Theme

**Comment by reduckted** [comment]
I've created #391 to fix this. It basically just applies the TextBox styles to the RichTextBox. It seems to do the job. Check it out and see if it does everything you need it to.

**Comment by scottcantwell** [comment]
> I've created #391 to fix this. It basically just applies the TextBox styles to the RichTextBox. It seems to do the job. Check it out and see if it does everything you need it to.

It worked!

![image](https://user-images.githubusercontent.com/90006729/202871590-72fab83b-a780-45de-abb0-78e2aabf58e8.png)
