### ISSUE TITLE
Recursively enumeration from Project gives me bin and obj dirs and its files

### ISSUE THREAD

**Issue by lsoft** [VsixCommunity/Community.VisualStudio.Toolkit#401]
but these directories ARE NOT in the project, they are not included at all!

as a result I receive `.g.cs` files and have no ways to distinguish which `cs` files written by user, by source gen, or by other VS tooling.

I need a way to exclude bin and obj folder from enumerating. The difficult that these folders may have different names and different projects types may store such info in different ways....

Any ideas are very welcome!

```C#
        public static List<SolutionItem> ProcessDownRecursivelyFor(
            this SolutionItem item,
            SolutionItemType type
            )
        {
            var result = new List<SolutionItem>();

            if (item.Type == type)
            {
                var fi = new FileInfo(item.FullPath);
                //now I have something like this, but it's ugly: if (fi.Extension.NotIn(".dll", ".exe", ".obj", ".pdb", ".pkgdef", ".config", ".json", ".imagemanifest", ".vsixmanifest", ".vsix"))
                {
                    result.Add(item);
                }
            }

            foreach (var child in item.Children)
            {
                if (child != null)
                {
                    result.AddRange(child.ProcessDownRecursivelyFor(type));
                }
            }

            return result;
        }
```

**Comment by lsoft** [comment]
Yes, I can to grab names for those folders:

```C#
            if(item is Community.VisualStudio.Toolkit.Project p)
            {
                var objFolder = await p.GetAttributeAsync("BaseIntermediateOutputPath");
                objFolder = objFolder?.Trim(' ', '\\', '/');

                var binFolder = await p.GetAttributeAsync("BaseOutputPath");
                binFolder = binFolder?.Trim(' ', '\\', '/');
```

so, probably, I can avoid enumerating inside them. But the question is still here: why the toolkit see these folders, if they are not in the project...

**Comment by reduckted** [comment]
A `SolutionItem` is a wrapper around an `IVsHierarchy` - essentially it's an item that appears in Solution Explorer. If you have _Show All Files_ enabled, then the `bin/` and `obj/` folders appear in Solution Explorer and will therefore be included when enumerating.

As an aside, the `Properties` and `References` nodes are also included when enumerating, and are "virtual folders".

You can determine whether a file is only there because _Show All Files_ is enabled by getting the value of the `VSHPROPID_IsNonMemberItem` property.

> Specifies that the item is not considered a member of the hierarchy. Required if the hierarchy supports (supersetted) views of its contents—that is, if ShowAllFiles displays files in directories that are not members of the project.

```cs
item.GetItemInfo(out IVsHierarchy hierarchy, out uint itemID, out _);

if (HierarchyUtilities.TryGetHierarchyProperty(hierarchy, itemID, (int)__VSHPROPID.VSHPROPID_IsNonMemberItem, out bool isNonMemberItem))
{
    if (isNonMemberItem) {
        // The item is not usually visible. Skip it.
    }
}
```

**Comment by lsoft** [comment]
@reduckted thanks, I will play with it, but it looks like that it makes sense to inculde such property by default in `SolutionItem`, because, to be honest, it is very unexpected behaviour))

**Comment by lsoft** [comment]
PR has merged. Closing as completed. Thanks @reduckted and @StevenRasmussen!
