### ISSUE TITLE
Possible to show markdown file in preview mode?

### ISSUE THREAD

**Issue by ErikEJ** [VsixCommunity/Community.VisualStudio.Toolkit#421]
With 17.5 we can now edit markdown files natively.

I have a dynamically generated .md file I would to show in the preview window - I am using:

      await VS.Documents.OpenInPreviewTabAsync(readmePath);

Is there any way I can open the markdown editor in "preview" mode?

**Comment by reduckted** [comment]
Do you want the equivalent of pressing the "Toggle Markdown Preview" button?
![image](https://user-images.githubusercontent.com/10321525/221475580-8fdfe959-17e9-4d4f-bac9-7f9a79eb83d5.png)

Or do you want the entire tab to show the preview?

**Comment by ErikEJ** [comment]
Ideally preview pane only. (Asking a lot...)

**Comment by reduckted** [comment]
I think you're out of luck either way. 😞 

The extension is located in `[INSTALL_DIR]\Common7\IDE\CommonExtensions\Microsoft\Markdown`.

If you take a look at the assemblies in [ILSpy](https://github.com/icsharpcode/ILSpy), you can see that it uses an editor margin for the preview button (so there isn't a command you can execute to open the preview) and an editor margin for the preview (so it's locked in to being side-by-side with the markdown editor).

**Comment by ErikEJ** [comment]
Never mind, it was a far stretch - thanks for investigating!
