### ISSUE TITLE
How to get the files selected by the mouse?

### ISSUE THREAD

**Issue by mirrortom** [VsixCommunity/Community.VisualStudio.Toolkit#422]
in the solution window , some file selected by the mouse , how to get them?
I didn't find an API for this , help.

var project = await VS.Solutions.GetActiveProjectAsync();
```
// think 
foreach (var item in project.Children)
{
    if(item.Selected == true)
        return item;
}

// think
project.SelectedItmes();
```
![help](https://user-images.githubusercontent.com/32234069/223653614-dd7854b6-b5f3-41b0-9444-1178d4b74abf.jpg)

**Comment by reduckted** [comment]
You can use `SolutionExplorerWindow`.

```c#
SolutionExplorerWindow? solutionExplorer = VS.Windows.GetSolutionExplorerWindowAsync();

if (solutionExplorer is not null) {
    foreach (SolutionItem item in await solutionExplorer.GetSelectionAsync()) {
        // ...
    }
}
```

**Comment by mirrortom** [comment]
I tried this API and it work! Thank you for your reply!
