### ISSUE TITLE
Replacement for the WPF Listview?

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#447]
In an effort to find a solution for the Listview Headers problem when VS Theming is enabled (see #433) I tried to discover what kind of control the VS Locals and other debugger windows are using.
They seem to be NOT using WPF but unmanaged code, or a special control with the windows classname "TREEGRID".
The properties windows inside VS use the Windows.Forms propertyGrid.
Further research located an assembly Microsoft.VisualStudio.VirtualTreeGrid which contains a VirtualTreeControl in the PrivateAssembies folder.
Has anybody used this?
Or should I simply write my own Windows Forms or native listview replaement?

**Comment by RobertvanderHulst** [comment]
To answer myself: I have switched to a DataGrid control. I have also included a file vsthemedirectory.xaml, based on the xaml that is included in the file Microsoft.VisualStudio.LanguageServices.dll .

**Comment by awschristou** [comment]
Hi @RobertvanderHulst if you're able/willing to share more details about your workaround, I'd be interested in understanding more about what you did. I'd like to consider doing something similar.

**Comment by RobertvanderHulst** [comment]
@awschristou You can find our solution here: 
https://github.com/X-Sharp/XSharpPublic/tree/feature/Intellisense/src/VisualStudio/Debugger.UI/Controls
The folder contains XAML code for 4 controls.
There is also a file VSThemeDictionary.xaml that derives the colors from the VS Shell, 
We're enabling theme support in the code behind. This could also be done in XAML of course.

The rest of the code in this assembly is a bit dirty. Our windows are for our debugger support and to fetch the data from the debuggee we are dynamically loading a DLL in the debuggee and we are calling methods in this DLL through the expression evaluator that serialize the objects that we need in the debugger. The same DLL is also referenced by the debugger UI to make sure that the class definitions are the same.
In this debugger UI we then deserialize the objects so we can display them in the debugger windows.
