### ISSUE TITLE
Extension method should be on ToolkitPackage not AsyncPackage

### ISSUE THREAD

**Issue by tonyhallett** [VsixCommunity/Community.VisualStudio.Toolkit#463]
ToolkitPackage has the internal AddToolWindow method
https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/5071b7e871e5ad3c585c858e35692f8debdb28f9/src/toolkit/Community.VisualStudio.Toolkit.Shared/ToolkitPackage.cs#L19

The extension method Invokes the Initialize method of `BaseToolWindow<>` with the AsyncPackage.
https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/5071b7e871e5ad3c585c858e35692f8debdb28f9/src/toolkit/Community.VisualStudio.Toolkit.Shared/ExtensionMethods/AsyncPackageExtensions.cs#L76

The Initialize method parameter is of type ToolkitPackage and invokes the AddToolWindow method.
https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/5071b7e871e5ad3c585c858e35692f8debdb28f9/src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/BaseToolWindow.cs#L70

**Comment by reduckted** [comment]
Good catch! #465 will fix this.
