### ISSUE TITLE
Where is `ToolkitToolWindowPane`?

### ISSUE THREAD

**Issue by Neme12** [VsixCommunity/Community.VisualStudio.Toolkit#494]
I got the [Extensibility Template Pack 2022 extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensibilityItemTemplates2022), created a new project from the template "VSIX Project w/Tool Window (Community)", and the project can't build :( There's a class deriving from `ToolkitToolWindowPane` but there's no `ToolkitToolWindowPane` available anywhere. What should I do?
![image](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/assets/11444821/8b5aa12b-4a45-436c-a07f-b196b58ad1b3)

**Comment by Neme12** [comment]
Oh I see someone had the same issue: #456 I updated the NuGet package and it works. But the template is still broken and should be fixed.

**Comment by madskristensen** [comment]
Just updated the nuget references in those templates

**Comment by Neme12** [comment]
Thanks
