### ISSUE TITLE
Can't create a custom base command class which inherits from BaseCommand<T> because it's abstract

### ISSUE THREAD

**Issue by yannduran** [VsixCommunity/Community.VisualStudio.Toolkit#5]
@reduckted, @madskristensen 

**Scenario:**

I wanted to convert some of my projects to use the _Community Toolkit_ instead of my _Luminous Code_ NuGet package. I want to use `ToolkitPackage` to benefit from the added tool window features.

My current commanding system relies on **_inheritance_** to achieve a single responsibility for each inherited class. It also has a far more intuitive way of handling `BeforeQueryStatus`, but I'll be doing a pull request to suggest using something similar.

In my extensions, I have an abstract base class (because it never get instantiated) which I call `PackageCommand`, which inherits from `AsyncCommandBase`. It has some logic in it that I want **all** of my commands to have available, as it checks in the package's options to see if all of the extension's commands should be enabled or not. 

> Note: the `AsyncCommandBase` is not currently really async, it was a work in progress

I then have additional base command classes for each **_group_** of commands that I want to enable/disable that inherit from that `PackageCommand` class. Let's say that I have two groups of commands, so `GroupOneCommand` and `GroupTwoCommand`. Each of those classes will will add some logic to look up the package's options to see if all of the commands in the group should be enabled or not.

**Problems:**

1. You can't currently inherit from `BaseComamnd<T>` (I don't see any way to do so due it being generic, or at the very least not the way I need to).
2. With the current implementation of `BaseComamnd<T>` I'd end up repeating the same code over and over (the whole reason that I wrote _Luminous Code_ was to **reduce** repeated code).

**Comment by madskristensen** [comment]
That's a tough one. How do you derive from `BaseCommand<T>` from an abstract class? I'm trying to figure it out

**Comment by yannduran** [comment]
It doesn't **have to be** _abstract_ though, that's just how I made it. It's in my own projects, not a library, so I know it's not meant to be instantiated.

I would just like to know how, or be able to inherit from the `BaseCommand<T>` class.

**Comment by reduckted** [comment]
I just want to make sure I'm understanding this correctly. You ideally want to have code that is something like this:

```csharp
public class ImplementationCommand : CommonCommand<ImplementationCommand>
{
    public ImplementationCommand() : base(new Guid("489ba882-f600-4c8b-89db-eb366a4ee3b3"), 0x0001) { }
}

public abstract class CommonCommand<T> : BaseCommand<T> where T : BaseCommand<T>
{
    public CommonCommand(Guid commandGuid, int commandId) : base(commandGuid, commandId)
    {
        // Do some common work...
    }
}
```

But you can't because:

> 'T' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'BaseCommand<T>'

In other words, `CommonCommand<T>` needs a type constraint on `T`, but it can't require `T` to inherit from `BaseCommand<T>` because `BaseCommand<T>` is abstract.

Have I understood that correctly?

**Comment by yannduran** [comment]
Yeah, I really should have supplied some code, eh.

> `ImplementationCommand : CommonCommand<ImplementationCommand>`

But you're right, the blocking part is that fact that `BaseCommand<T>` is abstract.

**Comment by reduckted** [comment]
Hmm, that is a tricky one. I can definitely see the usefulness of it, so it would be nice if we could find a solution. 

Here's a crazy thought. First, we loosen the type constraint from `where T : BaseCommand<T>, new()` to just `where T : new()`. This allows you to defined a base class that sits in between `BaseCommand` and your actual implementations. Next, we create a Roslyn code analyzer that verifies at compile time that anything inheriting `BaseCommand<T>` is inheriting it in the correct way:

```csharp
public class ImplementationCommand : CommonCommand<ImplementationCommand>
{
    public ImplementationCommand() : base(new Guid("489ba882-f600-4c8b-89db-eb366a4ee3b3"), 0x0001) { }
}

public abstract class CommonCommand<T> : BaseCommand<T> where T : CommonCommand<T>, new()
{
    public CommonCommand(Guid commandGuid, int commandId) : base(commandGuid, commandId)
    {
        // Do some common work...
    }
}

public abstract class BaseCommand<T> where T : class, new()
{
    // The existing BaseCommand<T> class, with only some casting when initializing.

    public static async Task<T> InitializeAsync(AsyncPackage package)
    {
        var instance = (BaseCommand<T>)(object)new T();
        // etc, etc...
        return (T)instance;
    }
}
```

Like I said, it's a crazy thought.

**Comment by yannduran** [comment]
> Here's a crazy thought. First, we loosen the type constraint from `where T : BaseCommand<T>, new()` to just `where T : new()`

I don't think that's all that crazy. I mean, yeah, ideally you'd want the constraint to include `BaseCommand<T>`, but if that's the only way to achieve inheritance, I'd say go for it. Not because it'd make my life easier, lol, but I think it'd be helpful to anyone or I wouldn't have brought it up.

> ```cs
> (BaseCommand<T>)(object)new T()
> ```

One thing I noticed, is that double cast really necessary? You can't just have `(BaseCommand<T>)new T()`?

**Comment by yannduran** [comment]
I did have a non-related thought. 

Would it not be better to supply the commandset gui **once** to the `ToolkitPackage` class, rather than having to supply it to **every** command class. I guess if you use the VSCT Intellisense extension it's not a **_huge_** deal to type in `PackgeGuids.PackageCommandset` for every command, but it's not exactly what I'd call **_best practice_**, which is a large part of what the toolkit's all about, right?

The `BaseCommand<T>` class already has a `Package` property, so why not make use of it to provide the commandset guid in the `InitializeAsync` method under the covers. It'd mean moving the code for storing the `CommandId` around a little, but again I think it'd be worth it. Is it even necessary to store the `CommandID`? I know that I've never needed it. But If you're saving the `commandGuid` and `commandID` instead, it could always be constructed again if needed. Or it could be saved as well, it's not a big deal. 

Doing this means that only the **package** needs to be supplied with the **commandset guid**, and **each command** only needs to be supplied with a **command id**. This is how I did it in _Luminous Code_.

**Comment by madskristensen** [comment]
I thought of that, but I think that will make the package class messier, and it won't encapsulate everything about the command handling to the command class itself.  What if the guid/id pairs were specified in attributes on the command class instead of in the constructor?

**Comment by madskristensen** [comment]
Ok, I've got an implementation that allows for multiple levels of inheritance and also eliminates the need to specify guid/id pairs in a constructor. It's super slick

**Comment by madskristensen** [comment]
Now a command can be implemented like this:

```c#
[Command(PackageGuids.guidTestExtensionPackageCmdSetString, PackageIds.RunnerWindowCommandId)]
internal sealed class RunnerWindowCommand : BaseCommand<RunnerWindowCommand>
{
    protected override async Task ExecuteAsync(OleMenuCmdEventArgs e)
    {
        await RunnerWindow.ShowAsync();
    }
}
```

**Comment by yannduran** [comment]
@madskristensen Whilst your implementation is **_impressive_**, I still believe it's the wrong approach. Developers don't actually **need** to even know that a command is made up of a _guid_ and and _id_, and they certainly shouldn't have to type it over and over. What about the DRY principle? And teaching developers about best practices?

My thinking was that a _package_ has a **_command set_**, while a _command_ has an **_id_** that gets combined with the package's command set.

**Comment by reduckted** [comment]
Is there ever a reason to create multiple command sets in an extension? It's just a way of grouping IDs, right? So there should be no problem with enforcing a single command set GUID for an extension.

**Comment by yannduran** [comment]
@reduckted 

I agree with you!

In 10 years of developing extensions the only time I've ever needed a second command set was when I wanted to have different extensions be added into the same toolbar/groups. I had them in a separate VSCT file that were included in the main one. Even then the values were only ever referred to in the main VSCT file itself, never for commands.

TBH I think it'd be quite weird to have more than one command set, unless I'm missing something.

**Comment by madskristensen** [comment]
I'm ok with that, but I'm not ready to put a limit in the toolkit to enforce a single commandset GUID. There might be some people that use more than one for organizational reasons or something like that. We could overload the `[Command(guid, id)]` attribute so it can also just take the id `[Command(id)]` if a guid is specified on the package level.

Now that I think about it, why not use the package guid instead of having a separate commandset guid?

**Comment by madskristensen** [comment]
I just tried it to make sure that it works, and it does. We don't need a separate command set guid and can just do this:

```xml
<GuidSymbol name="guidPackage" value="{05271709-8845-42fb-9d10-621cc8cffc5d}">
  <IDSymbol name="MultiInstanceWindow" value="0x0102" />      
</GuidSymbol>
```
