### ISSUE TITLE
[Question] WinUI support

### ISSUE THREAD

**Issue by shaggygi** [VsixCommunity/Community.VisualStudio.Toolkit#50]
Understanding this toolkit is an early concept, and the fact that WinUI 3 has not RTMed, are there thoughts around adding support for WinUI views/controls to this toolkit?

**Comment by mrlacey** [comment]
I don't believe Visual Studio supports creating embedded UI with WinUI 3.


BTW. WinUI3 has RTM'd. The version numbering is confusing but it is fully supported for production apps. https://docs.microsoft.com/en-us/windows/apps/winui/winui3/

**Comment by shaggygi** [comment]
> BTW. WinUI3 has RTM'd. The version numbering is confusing but it is fully supported for production apps.

Thanks for pointing out.  I'm still a little confused on the whole roadmap and Project Reunion stuff 🤕

**Comment by yannduran** [comment]
I'd certainly like to know if WinUI3 is currently supported for use in VS extension UI, or if not if that's something that will happen and when. @madskristensen do you know?

**Comment by StevenRasmussen** [comment]
I don't think that native support for WinUI3 will be possible until VS moves away from the full .Net Framework to .Net 5+, which as I understand it isn't on the table yet.  After 64bit and VS 2022 it could become a possibility.  You might be able to get something to work out of process but it wouldn't be very seamless.

**Comment by shaggygi** [comment]
> VS moves away from the full .Net Framework to .Net 5+, which as I understand it isn't on the table yet. 

Referencing #56

**Comment by madskristensen** [comment]
This won't be possible for now. Closing

**Comment by yannduran** [comment]
Wow Mads, that's such a Microsoft thing to do, closing an issue just because it's not **_currently_** possible. That's how ideas get lost.

Very disappointing to see you doing what you say you've stopped from happening in the Developer Community website.

**Comment by madskristensen** [comment]
@yannduran *currently* refers to the time between now and the potential future of VS being converted to running on .NET 5/6/7/8. There is nothing wrong with the idea, but it is not actionable in any known time horizon or may not ever be relevant depending on the future architecture of VS. If that's not a ok reason to close an issue, then what is?

**Comment by yannduran** [comment]
The question was about **WinUI support**, not about _VS being converted to running on .NET 5/6/7/8_, which I understand is not currently even on the radar.

>_I'd certainly like to know if WinUI3 is currently supported for use in VS extension UI, or if not if that's something that will happen and when. @madskristensen do you know?_

My two questions went unanswered as well, and I don't believe the OP's issue has been adequately addressed as your reply addressed something completely different to what was asked.

>_If that's not a ok reason to close an issue, then what is?_

Aren't issues there to be used as a sort of backlog? You close there issue, they get lost, and there's no incentive to keep following it up. You agreed that this shouldn't happen in the Developer Community website, why not the same here?
