### ISSUE TITLE
Include Dialog in VS.Notifications Show methods

### ISSUE THREAD

**Issue by shaggygi** [VsixCommunity/Community.VisualStudio.Toolkit#51]
Since it is a partial class, would it make it clearer if 'Dialog' (or 'MessageBox') was added to the end of the Show methods?  For example...

```csharp
VS.Notifications.ShowConfirmDialog("title", "message");
VS.Notifications.ShowErrorDialog("title", "message");
VS.Notifications.ShowMessageDialog("title", "message");
VS.Notifications.ShowWarningDialog("title", "message");
```

**Comment by yannduran** [comment]
Sorry, but I disagree. There's no need for `Dialog` to be appended to these methods. The intent is already there in `ShowError`, `ShowMessage`, `ShowWarning` and `ShowConfirm` (although I'd actually prefer `GetConfirmation`). The verb is `Show` and the nouns are `Error`, `Message` and `Warning`. Adding `Dialog` just makes them unnecessarily complicated.  The toolkit aims for simple and easy, not complicated and wordy.

This was one of the first bits of code to be added to the work that Mads did on the toolkit, and came from my **_Luminous Code_** methods. Mads merged the code before I had a chance to add the methods as I intended. I have some reworking of these methods to do as soon as I get the time.

I'd actually like to go one step further and suggest that these are such fundamental methods that they should be directly off VS, as in `VS.ShowError` etc, just like `VS.GetService<>`. But I'll address that in the PR that I create for the updated methods.

**Comment by shaggygi** [comment]
Understood.  Was mainly trying to differentiate as some might think `ShowXXX` could be sent to status bar, infobar, etc.  It might help by moving to VS namespace as mentioned.

I would suggest, that if renaming to `GetConfirmation`, it should also be renamed to `ShowConfirmation` to be consistent.

**Comment by StevenRasmussen** [comment]
I think there could be some validity to renaming things based on what @shaggygi mentioned regarding different approaches to how a 'Notification' could be displayed (status bar, infobar, toast message etc).  Perhaps a rename of the namespace/class might be more appropriate though from `VS.Notifications` to `VS.Dialogs` or `VS.Windows`.  Naming is pretty subjective though and people have lots of opinions ;).  Just my 2 cents.

**Comment by StevenRasmussen** [comment]
@madskristensen - Any thoughts on this?  Do you feel any changes are necessary or should we close this? If it looks like some changes are required I'm happy to work on them and submit a PR.

**Comment by madskristensen** [comment]
I haven't given it much thought, but I do think that something like `ShowError` isn't enough to explain that it is a message box.

**Comment by StevenRasmussen** [comment]
I like the idea of hiding/abstracting the `VsShellUtilities.ShowMessageBox` method myself in favor of the current `Notifications` methods but I agree that a refactor of some sort would be beneficial to both:
1) Provide clearer intent of what `Notifications.ShowMessage` actually does
2) Provide for other ways of showing a `Message` via the status bar, infobar or other

**Comment by madskristensen** [comment]
So we could rename `ShowMessage` to `ShowMessageBox` which better sets expectations. We could prepend the word `Box` to the other methods such as `ShowError` so it would become `ShowErrorBox`. Or ditch the other methods altogether?

**Comment by StevenRasmussen** [comment]
I like my idea of changing namespaces in my comment [here](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/51#issuecomment-856079603) - 😁!  But I'm fine with changing names as well if that's what everyone likes more.  It just means that as we add more functionality in the `Notifications` namespace that we're naming things like:
`ShowStatusBarMessage`
`ShowInfoBarMessage`.  

With the namespace change it would be something like:
`VS.Dialogs.ShowMessage`
`VS.StatusBar.ShowMessage`
`VS.InfoBar.ShowMessage` etc.

**Comment by madskristensen** [comment]
Somehow, I missed the namespace idea. I really like it. I'm in favor of doing that.

**Comment by yannduran** [comment]
Sorry to be replying late in this. I'm glad you guys liked Steven's idea of using **namespaces**, not just appending `Box` to everything.

`ShowMessage` might not always be implemented using a message box. Methods should be named after **_what they achieve_**, not **_how_** they achieve the functionality.
