### ISSUE TITLE
How to rename project name？

### ISSUE THREAD

**Issue by vincedan** [VsixCommunity/Community.VisualStudio.Toolkit#513]
Any hint or instruction for renaming projectname in vs extension?
thanks, guys

**Comment by RobertvanderHulst** [comment]
Renaming the project means renaming the project file. Is that what you want?
Or do you want to change the caption of the project in the Solution Explorer?

**Comment by vincedan** [comment]
> Renaming the project means renaming the project file. Is that what you want? Or do you want to change the caption of the project in the Solution Explorer?
@RobertvanderHulst , I want to implement a function, which is the same as changing the caption (filename without suffix ?) in solution explorer.

**Comment by RobertvanderHulst** [comment]
I am unsure if it works, but you could try getting the Hierchy and setting the __VSHPROPID.VSHPROPID_Caption to the new name you want to show in the Solution Explorer.
Call GetItemInfo() on the project object to get the IVSHierarchy and itemId.
Then call SetProperty on the IVSHierarchy object and pass it the itemId,  __VSHPROPID.VSHPROPID_Caption  and the new caption.

**Comment by vincedan** [comment]
thanks, @RobertvanderHulst , have tried your suggestion, and failed... :(   I can get  project Caption by GetProperty method. maybe there are some limitations for project item node.
`hierarchy.GetProperty(itemId, (int)__VSHPROPID.VSHPROPID_Caption, out object projectName);`

right now I use DTE.Project interface to implement this requirement although it seems DTE is too staled..
