### ISSUE TITLE
InvalidCastException when accessing solution explorer

### ISSUE THREAD

**Issue by StefanOverHaevgRZ** [VsixCommunity/Community.VisualStudio.Toolkit#518]
I try to access the solution explorer to get the currently selected items:
```cs
var solutionExplorer = await VS.Windows.GetSolutionExplorerWindowAsync();
if (solutionExplorer is null)
    return null;

var solutionItems = await solutionExplorer.GetSelectionAsync();
// ...
```

However, the `GetSolutionExplorerWindowAsync` already throws a `InvalidCastException`:
> Unable to cast object of type `Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPaneMarshaler` to type `Microsoft.VisualStudio.Shell.Interop.IVsSolutionUIHierarchyWindow`.

Looks like this is caused by this cast in the [`SolutionExplorerWindow.ctor`](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/cc8820222371d2c3a8fae46d63d6edc29c597e3e/src/toolkit/Community.VisualStudio.Toolkit.Shared/Windows/SolutionExplorerWindow.cs#L23):
```cs
SolutionUIHierarchyWindow = (IVsSolutionUIHierarchyWindow)window;
```

**Environment**
- Two shell projects, one for VS 2019 and one for VS 2022.
- Shared project referenced by both shell projects.
- Both projects reference `Community.VisualStudio.Toolkit.16`.

**Comment by RobertvanderHulst** [comment]
Stefan,
You should use `Community.VisualStudio.Toolkit.17` for VS 2022

Robert

**Comment by StefanOverHaevgRZ** [comment]
@RobertvanderHulst I tried, but then it won't compile any longer:
![image](https://github.com/user-attachments/assets/67d0ec1c-e33d-4201-be8c-7b3e1707ec7d)
It does not recognize any of the Toolkit namespaces and types then.

I found a comment around here that said to reference the lowest targeting version of the Toolkit (16 in my case).

**Comment by ErikEJ** [comment]
@StefanOverHaevgRZ You cannot mix VS 2019 and VS 2022 like that  - two different universes

**Comment by RobertvanderHulst** [comment]
@StefanOverHaevgRZ: what @ErikEJ  said. VS 2022 is Framework Net48 and 64 bits. VS 2019 is 32 bits and Net472,

**Comment by StefanOverHaevgRZ** [comment]
@RobertvanderHulst @ErikEJ Having shared code in a shared project between VS 2019 and VS 2022 works fine 👍 

It's the .NET Framework version I missed to upgrade on the 2022 project. Thank you!
