### ISSUE TITLE
FontSize inconsistency

### ISSUE THREAD

**Issue by gmit3** [VsixCommunity/Community.VisualStudio.Toolkit#523]
The font size set and previewed in the VS Options dialog is not the same font size seen in the 'Fonts and Colors Windows'. To get the font as large as Environment font size 8, I need to set 'Top Left' font size to 12 (which looks huge in the preview in the Options dialog).

It doesn't seem to be DPI-dependent.

I believe some calculation is missing, but I have no idea what it might be (it's not px/pt)...
![image](https://github.com/user-attachments/assets/8a1988c1-12e0-4446-b8ed-fc69f6418d59)

**Comment by gmit3** [comment]
For VS Options font size 8, I see 11.5 is set as FontSize.

For 9, I get 13.
For 12, I get 17.
For automatic, I get 12.

The ratio doesn't seem to be constant (maybe due to rounding, but the coefficient is still strange).

My DPI is 200%, so it doesn't seem to be related to that.

**Comment by reduckted** [comment]
Hmm, that's very strange. I've never noticed it before, but you're right, the font size doesn't match. I'm using 100% scaling, so like you suggested, it's not related to DPI scaling.

**Comment by gmit3** [comment]
I believe I've figured it out.

IVsFontAndColorStorage.GetFont returns FontInfo and LOGFONTW - FontsAndColors.cs use only FontInfo.

So, for VS Options fonts size 8, FontInfo.wPointSize also contains 8, converted from px to pt is 10.67, which is too small for the FontSize property that VS uses for its WPF controls.

To calculate VsFont.EnvironmentFontSize, Microsoft.Internal.VisualStudio.Shell uses:
    private double FontSizeFromLOGFONTHeight(int lfHeight)
    {
      return (double) Math.Abs(lfHeight) * 96.0 / DpiAwareness.SystemDpiY;
    }
for conversion.

So, in my case, for font size 8, I get -23 as LOGFONTW.lfHeight, DpiAwareness.SystemDpiY is 192 which gives 11.5 for the FontSize, which is correct.

For font size 9, I get -26, which is 13 (correct), and for font size 12, I get -34, which becomes 17 (also correct).


The trouble for me is 'automatic' - if selected, I presume System.Windows.SystemFonts.MessageFontSize should be used (12, as VS does), but I don't seem to get FontDefinition.Automatic.FamilyName in fi.bstrFaceName... I need to check if I've modified something while experimenting...

**Comment by reduckted** [comment]
> I believe I've figured it out.

Excellent! Should be fixed by #524. I've adjusted the `ConfiguredFont` class to use the `LOGFONTW` to calculate the font size to use in WPF, and I've added a new `PointSize` property that contains what used to be in the `Size` property.

**Comment by gmit3** [comment]
Cool.

I will also put my observations on 'Automatic' that I haven't verified yet on this sample (sorry), but I see in my code that it doesn't behave as intended (I've used it as a template).

For 'Automatic', GetFont returns what was selected before automatic was selected; I never get the font name to be 'automatic'.

However, if I do IVsFontAndColorStorage.OpenCategory without __FCSTORAGEFLAGS.FCSF_LOADDEFAULTS, then GetFont will fail with:
  const int REGDB_E_KEYMISSING = unchecked((int)0x80040152);
when 'Automatic' is selected.

Then I can use:
  FindResource("VsFont.EnvironmentFontFamily") as System.Windows.Media.FontFamily
and
  FindResource("VsFont.EnvironmentFontSize") as double?

to set correct values for font...

**Comment by reduckted** [comment]
> I will also put my observations on 'Automatic' that I haven't verified yet on this sample (sorry), but I see in my code that it doesn't behave as intended (I've used it as a template).
> 
> For 'Automatic', GetFont returns what was selected before automatic was selected; I never get the font name to be 'automatic'.

I can't say that I have the same problem. In my trials, changing between Automatic and some other font works correctly.

If you can put together a reproduction and create a new issue, we can try to identify what the problem might be.

**Comment by gmit3** [comment]
Ah, disregard my last comment, at least for now, but with demo sources, I cannot get Automatic at all because 
    DemoFontAndColorCategory() : base(new FontDefinition("Consolas", 12))
provides font, and __FONTCOLORFLAGS.FCF_AUTOFONT never gets set.

If this initialization is replaced with FontDefinition.Automatic, it works correctly in all cases I've tried.
