### ISSUE TITLE
[Question] .NET (Core) Support

### ISSUE THREAD

**Issue by shaggygi** [VsixCommunity/Community.VisualStudio.Toolkit#56]
I noticed the project templates create the older project system style that targets .NET 4.7.2.  Are there plans to move this to .NET (Core) 5+?  Also, is there any news on moving the VS SDK to .NET (Core) 5+?

For instance, I noticed [Microsoft.VisualStudio.GraphModel](https://www.nuget.org/packages/Microsoft.VisualStudio.GraphModel) doesn't appear to have a .NET Standard/Core offering.

**Comment by madskristensen** [comment]
VS 2022 is still running on .NET framework. As long as it does that, the VSSDK has to as well.

**Comment by StevenRasmussen** [comment]
I know this isn't directly related to .Net Core/5+ support... but I thought it might be a good place to make people aware of [PolySharp](https://github.com/Sergio0694/PolySharp), which lets you use the latest C# features while still targeting .Net Framework, which is still required for VS extensions.
