### ISSUE TITLE
Themes.UseVsTheme doesn't appear to apply to TextBlock

### ISSUE THREAD

**Issue by awschristou** [VsixCommunity/Community.VisualStudio.Toolkit#57]
I'm using the Blue theme in Visual Studio. If I add a TextBlock containing text to ThemeWindowDemo.xaml as follows
```
            <TextBlock Margin="{StaticResource Margin}">
                <TextBlock Text="Click here: " />
                <Hyperlink>Interesting link</Hyperlink>
            </TextBlock>
```

The TextBlock is barely legible. I suspect it is rendering as almost-white text on white background (sample image below). Would it be appropriate for TextBlocks to be handled by Themes.UseVsTheme?

![image](https://user-images.githubusercontent.com/39839589/121050413-67193500-c76d-11eb-8302-0e9341305c31.png)

**Comment by madskristensen** [comment]
You should use a Label instead

**Comment by awschristou** [comment]
In my use case, TextBlocks are used for informational content, and make use of text wrapping and trimming. Should these be revised away from using TextBlocks, or would your guidance be to explicitly handle TextBlock foregrounds to match the theme in these cases?

**Comment by madskristensen** [comment]
It was more meant as a workaround. We should add support for TextBlock. It's easy to do

**Comment by yannduran** [comment]
> We should add support for TextBlock. It's easy to do

Yes, absolutely!

**Comment by reduckted** [comment]
Weird. I thought it handled `TextBlocks`. Maybe `StartPageTextBodyBrushKey` isn't the correct foreground brush to use. 🤔
