### ISSUE TITLE
Community.VisualStudio.Toolkit.VS.Events don't work in VS2022

### ISSUE THREAD

**Issue by tom-englert** [VsixCommunity/Community.VisualStudio.Toolkit#63]
Using the following code:
```
var events = Community.VisualStudio.Toolkit.VS.Events;
events.DocumentEvents.DocumentSaved += DocumentEvents_DocumentSaved;
```
Generates this exception when run in VS2022:
```
Exception thrown: 'System.MissingMethodException' in Test.dll
Method not found: 'Void EnvDTE._dispDocumentEvents_DocumentSavedEventHandler..ctor(System.Object, UIntPtr)'.
```

This happens for all the events.

**Comment by madskristensen** [comment]
I'm rewriting the class to stay clear of the DTE

**Comment by tom-englert** [comment]
Great! That will solve all my migration issues

**Comment by madskristensen** [comment]
You can try it now using the CI NuGet feed (See readme)

**Comment by madskristensen** [comment]
I've replaced all DTE events with IVs* equivalents

**Comment by yannduran** [comment]
Are you saying that even DTE2 didn't allow the code to work?

**Comment by tom-englert** [comment]
@yannduran yes, none of the dte2 events work

**Comment by yannduran** [comment]
@tom-englert thanks for that!

**Comment by ryanmolden** [comment]
There were numerous 64 bit issues in the old PIAs and this release of Visual Studio has moved to a new unified PIA with incorrect APIs fixed. As such it is not supported to build an extension that references the old PIAs but runs in this version of Visual Studio. This difference (where the Roslyn compiler has emitted a different delegate ctor signature than the original tlbimp did) is one such issue with doing that. The supported mechanism is to recompile targeting the new PIAs.
