### ISSUE TITLE
Add utility method for firing command

### ISSUE THREAD

**Issue by madskristensen** [VsixCommunity/Community.VisualStudio.Toolkit#64]

**Comment by reduckted** [comment]
I've previously written an implementation of this here;
 https://github.com/reduckted/ProjectFilter/blob/b1e2681b41086fb3fba0c65774202bf593deb576/source/ProjectFilter/Services/FilterService.cs#L360

Probably just needs to change how the logging is done, if it's even needed at all.

**Comment by madskristensen** [comment]
Thanks. I hoped to find one that doesn't require the use of DTE. Not sure what service lets me find commands by name, though...
