### ISSUE TITLE
Find a way to add existing file to a solution folder without the DTE

### ISSUE THREAD

**Issue by madskristensen** [VsixCommunity/Community.VisualStudio.Toolkit#84]
@bluetarpmedia do you have an idea on how to do that?

**Comment by bluetarpmedia** [comment]
I think a solution folder is treated like an IVsProject, so I think you can just cast the IVsHierarchy to an IVsProject like you do for this case:

`else if (Type == NodeType.Project || Type == NodeType.PhysicalFolder || Type == NodeType.PhysicalFile)`

`var ip = (IVsProject4)_hierarchy;`

**Comment by madskristensen** [comment]
I get a weird Argument out of range exception when I call AddItem on a solution folder cast as an IVsProject

**Comment by madskristensen** [comment]
Ok, I got some reference code that seems to be able to do the trick...
