### ISSUE TITLE
VS.Services.GetCommandServiceAsync does not work

### ISSUE THREAD

**Issue by reduckted** [VsixCommunity/Community.VisualStudio.Toolkit#92]
The `VS.Services.GetCommandServiceAsync()` method does not seem to ever work because the service is never found.

I don't know why, but it seems that the `IMenuCommandService` can only be retrieved from a `Package` and not from the global service provider.

```cs
IMenuCommandService fromGlobal = await VS.GetServiceAsync<IMenuCommandService, IMenuCommandService>();
IMenuCommandService fromPackage = await this.GetServiceAsync<IMenuCommandService, IMenuCommandService>();
// `this` is a Package object.

await VS.MessageBox.ShowAsync(
    "From Global: " + ((fromGlobal is null) ? "null" : "not null") + "\r\n" +
    "From Package: " + ((fromPackage is null) ? "null" : "not null")
);
```

![image](https://user-images.githubusercontent.com/10321525/124339548-91d29e00-dbf2-11eb-871d-b4dbf295c15f.png)

**Comment by madskristensen** [comment]
I noticed that too. @AArnott do you know why and if there's a workaround?

**Comment by madskristensen** [comment]
I noticed that too. @AArnott do you know why and if there's a workaround?

**Comment by AArnott** [comment]
I don't know. @ryanmolden?

**Comment by ryanmolden** [comment]
There is no such thing as a 'global' menu service, menu service objects are package / toolwindow specific abstractions that facilitate registering handlers at that scope, they are ONLY available from the package / toolwindow as service provider.

**Comment by madskristensen** [comment]
Interesting. I had no idea. Thanks for educating us on that, @ryanmolden
