### ISSUE TITLE
Breaking changes ?

### ISSUE THREAD

**Issue by RobertvanderHulst** [VsixCommunity/Community.VisualStudio.Toolkit#94]
Mads,

I like the idea of the Community Toolkit a lot, but I am hesitating to use it for our projects for the following reason:

we had a dependency in our extension to Mono.Cecil and everything worked great until one user used it on a VS installation that also had Xamarin installed. It appeared that the Xamarin team had used an older version of Mono.Cecil, and even though we had clearly indicated using a ProvideCodeBase attribute that we depended on a specific version of Mono.Cecil and we had included that version in our extension, Vs still decided to load the older version of Mono.Cecil which broke our code.
We resolved that now by adding "our own version" of mono.cecil with another assembly name.

How do we prevent a similar problem with the Community toolkit?
I monitored some of the commits from the last month and I see several commits that make breaking changes. 
If we had a dependency on the toolkit and another extension has a dependency to a different version then there would be same problems again.
I see only 2 solutions:
- The Toolkit code never makes breaking changes
- We include the toolkit in our code and create our own assembly from it.

How do you look at this ?

Robert

**Comment by madskristensen** [comment]
We actually had that issue in the very first versions of this toolkit and `ProvideCodeBase` didn't seem to make a difference. But with the help from the Visual Studio team we quickly discovered that `ProvideCodeBase` doesn't work at all unless the .dll it points to is signed. 

To fix this we signed the assemblies:

```xml
<SignAssembly>true</SignAssembly>
<AssemblyOriginatorKeyFile>../key.snk</AssemblyOriginatorKeyFile>
```

and the toolkit NuGet package automatically adds the following to be compiled in the consuming project:

```csharp
using Microsoft.VisualStudio.Shell;

[assembly: ProvideCodeBase(AssemblyName = "Community.VisualStudio.Toolkit")]
```

And now we can run multiple versions of the toolkit in the same open instance of VS without conflicts.

**Comment by RobertvanderHulst** [comment]
Thanks Mads, this helps.

I have one more question.
I am trying to remove all DTE access from our project system now to prepare for VS2022.

Our "old" project system is based on the MPF code. Part of that code is an automation layer that we expose so the Windows Forms editor and other VS components can call back into our project system and for example ask for the list of references in our projects or for the output file name of the project. 
These classes all implement some EnvDTE interfaces such as EnvDTE.Project. One of the properties in many of the EnvDTE interfaces is the DTE property.
What is the recommended way of returning this DTE property? Should we simply return the DTE2 object and cast that to DTE ? Or is there a better way to do this ?

**Comment by madskristensen** [comment]
If you can cast e.g. `ProjectItem.DTE` to `DTE2` successfully, then do that. I haven't tried so don't know if that will work. Otherwise, don't use the `DTE` properties and pass the `DTE2` instance around instead. Only `DTE2` will cross the 16.0/17.0 barrier. However, some of the events like `DTE2.Events.WindowEvents` still won't work when crossing the barrier.

**Comment by StevenRasmussen** [comment]
Maybe we can close this one?
