### ISSUE TITLE
Replacement for DTE2.ToolWindows.SolutionExplorer

### ISSUE THREAD

**Issue by reduckted** [VsixCommunity/Community.VisualStudio.Toolkit#98]
I'm looking to see whether the Solution Explorer contains any items. See here:

https://github.com/reduckted/ProjectFilter/blob/b1e2681b41086fb3fba0c65774202bf593deb576/source/ProjectFilter/Services/SolutionLoadObserver.cs#L44-L55

What I'm doing might be a bit of a hack, but I'm executing a bunch of commands that operate on the Solution Explorer tool window to hide unloaded projects. If Solution Explorer hasn't been populated, then I wait a bit and try again. 

I also need to activate the Solution Explorer window ([see here](https://github.com/reduckted/ProjectFilter/blob/b1e2681b41086fb3fba0c65774202bf593deb576/source/ProjectFilter/Services/FilterService.cs#L323)) to allow those commands to work, and get the selection ([see here](https://github.com/reduckted/ProjectFilter/blob/b1e2681b41086fb3fba0c65774202bf593deb576/source/ProjectFilter/Services/FilterService.cs#L391)) so that I can restore the selected items afterwards.

I see there's an `IVsSolutionUIHierarchyWindow`, but it doesn't seem to provide access to the hierarchy in the window, and I can't find a corresponding `SVsSolutionUIHierarchyWindow` type.

**Comment by madskristensen** [comment]
What are the main use cases for the DTE SolExp today? I'm wondering if a full replacement is needed
